---
- name: Disable firewalld
  become: true
  systemd:
    name: firewalld
    state: stopped
  ignore_errors: true

- name: Remove firewalld
  become: true
  dnf:
    name: firewalld
    state: absent

- name: Policy ACCEPT
  become: true
  ansible.builtin.iptables:
    chain: INPUT
    policy: ACCEPT

- name: Iptables flush filter
  become: true
  ansible.builtin.iptables:
    chain: "{{ item }}"
    flush: yes
  with_items:  [ 'INPUT']

- name: Allow related and established connections
  become: true
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    rule_num: 1
    action: insert

- name: Allow loopback
  become: true
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: Whitelist Ports Backend
  become: true
  ansible.builtin.iptables:
    chain: INPUT
    source: 0.0.0.0/0
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
  loop:
    - 2442

- name: Policy DROP
  become: true
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP

- name: Save current state of the firewall in system file
  become: true
  community.general.iptables_state:
    state: saved
    path: /etc/iptables/rules.v4
